
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-[#016FB9] text-white font-bold font-mono" lang="en">
      <body className="flex" >{children}</body>
    </html>
  );
}
